version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env.development
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - api

  api:
    build: .
    image: node-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: "npm start"
    env_file: .env.development
    volumes:
      - ./:/app
    networks:
      - api

volumes:
  database:

networks:
  api:
    driver: "bridge"